sudo: false
language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
python: 2.7
env:
    - TOX_ENV=py26-django16
    - TOX_ENV=py27-django14
    - TOX_ENV=py27-django15
    - TOX_ENV=py27-django16
    - TOX_ENV=py27-django17
    - TOX_ENV=py27-django18
    - TOX_ENV=py33-django16
    - TOX_ENV=py33-django17
    - TOX_ENV=py33-django18
    - TOX_ENV=py34-django16
    - TOX_ENV=py34-django17
    - TOX_ENV=py34-django18
    - TOX_ENV=py35-django18
matrix:
    fast_finish: true
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
